/*
     Array - It is a collection of elements of same data type

	int x[5]={10,20,30,40,50};

	   x[0] = 10
	   x[1] = 20
	   x[2] = 30
	   x[3] = 40
	   x[4] = 50
*/

   #include<iostream.h>
   #include<conio.h>

   void main()
   {
      int x[]={10,20,30,40,50};

       clrscr();

    for(int i=4 ; i>=0 ; i--)
    {
	cout<<"\n\n "<<x[i];
    }

       getch();
   }













